# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('roleID', models.IntegerField()),
                ('userName', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('staffID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Staff')),
            ],
        ),
    ]
