# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170322_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStruct',
            fields=[
                ('acadYear', models.IntegerField(primary_key=True, serialize=False)),
                ('vanFee', models.IntegerField(null=True)),
                ('termFee', models.IntegerField(null=True)),
                ('startYear', models.IntegerField(null=True)),
                ('classNumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1),
        ),
    ]
