# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170322_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currentYear',
            field=models.IntegerField(null=True),
        ),
    ]
