# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170322_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=50)),
                ('lessonPlan', models.CharField(max_length=50)),
            ],
        ),
    ]
