# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20170322_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='addrID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
