# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20170328_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='addrID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='cID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Contact'),
        ),
    ]
