# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20170409_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=1),
        ),
    ]
