# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20170409_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestruct',
            name='id',
        ),
        migrations.AlterField(
            model_name='feestruct',
            name='acadYear',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
