# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170315_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNumber', models.IntegerField(null=True)),
                ('numberSections', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(null=True)),
                ('sectionName', models.CharField(max_length=2, null=True)),
                ('classNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(null=True)),
                ('classNumber', models.IntegerField(null=True)),
                ('feesToBePaid', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AddField(
            model_name='address',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phoneNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='addrID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[(b'A', b'Accountant'), (b'H', b'Head Accountant'), (b'C', b'Correspondent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='addrID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Address'),
        ),
        migrations.AddField(
            model_name='parent',
            name='cID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Contact'),
        ),
        migrations.AddField(
            model_name='parent',
            name='studentID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
    ]
