# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170322_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='positions',
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
