# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_student_currentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestruct',
            name='acadFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestruct',
            name='termFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestruct',
            name='vanFee',
            field=models.IntegerField(default=0),
        ),
    ]
