# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170322_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=50)),
                ('lessonPlan', models.CharField(max_length=50)),
            ],
        ),
    ]
