# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_correspondent_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correspondent',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
