# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20170327_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Staff'),
        ),
    ]
