# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20170329_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salaryToBePaid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
