# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_staff_salarytobepaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConReqest',
            fields=[
                ('conID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=2)),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('fundID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=2)),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RemReqest',
            fields=[
                ('remID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=2)),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
            ],
        ),
    ]
