# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_conreqest_financialreport_fundrequest_remreqest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conreqest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conreqest',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='remreqest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='remreqest',
            name='status',
            field=models.IntegerField(),
        ),
    ]
