# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20170404_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.AddField(
            model_name='user',
            name='isParent',
            field=models.IntegerField(default=0),
        ),
    ]
