# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20170404_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
