# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20170409_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestruct',
            name='acadYear',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='feestruct',
            name='classNumber',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
